Sasino97/gta-cnr-localization

- businesses.xml
- death.xml
* Add (more) translations for businesses.xml
* Translate 'revenge' in death.xml
> Add (more) nl-NL localization

- death.xml
- properties.xml
- specialitems.xml
If #8 is to be merged, then this will 100% nl-NL as of right now 🎉
> Finish remaining nl-NL translation for death/properties/specialitems

- jobs.xml
Additional:
[en-US] Change formatting to end with ~s~ for police exam questions.
> [nl-NL] Translate Police Exam to Dutch.

- businesses.xml
- imenu.xml
- jobs.xml
- main.xml
Also:
[en-US} Fix robbery_shoplifting_success to allow color formatting at different places
> [nl-NL] Robbery strings translated

- chatnotifications.xml
- imenu.xml
- main.xml
[en-US] Change "GTA CnR" to "CNR V" in imenu
> [nl-NL] Translate help menu + blocking strings

- businesses.xml
- jobs.xml
- main.xml
- player.xml
> Completed remaining translations for nl-NL

- banking.xml
- businesses.xml
- imenu.xml
- jobs.xml
- main.xml
- player.xml
- properties.xml
Latest additions from 07/25/2024 100% complete
> [fr-FR] businesses.xml, imenu.xml, jobs.xml, main.xml, player.xml, properties.xml (latest additions)

- businesses.xml
- chatnotifications.xml
- imenu.xml
- main.xml
- player.xml
- properties.xml
…layer.xml and properties.xml - Updated
> [hi-Latn] business.xml, chatnotifications.xml, imenu.xml, main.xml, player.xml and properties.xml - Updated

- businesses.xml
- chatnotifications.xml
- death.xml
- imenu.xml
- jobs.xml
- main.xml
- player.xml
- properties.xml
- specialitems.xml
- vehicles.xml
added missing de-DE translations to main.xml, death.xml, business.xml, imenu.xml, jobs.xml, player.xml
> german translation

- businesses.xml
- main.xml
> Party system localization

- chatnotifications.xml
- player.xml
- properties.xml
- specialitems.xml
chatnotifications.xml
players.xml
properties.xml
specialitems.xml
> New Italian Translations

- chatnotifications.xml
- imenu.xml
- main.xml
> Replaced language ISO codes

- businesses.xml
- death.xml
- imenu.xml
- jobs.xml
- main.xml
- player.xml
- vehicles.xml
Adds strings related to delivery jobs + bonus corrections
> Adds strings related to delivery jobs + bonus corrections

- businesses.xml
- death.xml
- imenu.xml
- jobs.xml
- main.xml
- player.xml
Added missing german translations in: businesses.xml, death.xml, imenu.xml, jobs.xml, main.xml, player.xml
> de-DE translations

- businesses.xml
- vehicles.xml
> update business.xml ar-001

- businesses.xml
> business.xml ar-001

- readme.md
> Update readme.md to point to the PR explanation thread

- banking.xml
- vehicles.xml
finished banking translation and tweaked vehicle translation
> Banking.xml vehicles.xml

- businesses.xml
- death.xml
- imenu.xml
- jobs.xml
- main.xml
- player.xml
Added de-DE translations to businesses.xml, death.xml, imenu.xml, jobs.xml, main.xml, player.xml
> Added missing de-DE translations

- businesses.xml
- chatnotifications.xml
Old changes that wasn't merged+some new translations
> businesses.xml ,  chatnotifications.xml - ar-001

- death.xml
- player.xml
- properties.xml
- specialitems.xml
- vehicles.xml
full translation of player.xml and properties.xml
fix of one string in death.xml
> [lv-LV] player, properties, specialitems, vehicles

- businesses.xml
- chatnotifications.xml
- death.xml
- imenu.xml
Finished all missing lines in the 3 files in the title
> [ar-001] Completed businesses.xml , death.xml and imenu.xml 

- businesses.xml
- imenu.xml
- jobs.xml
- main.xml
- player.xml
fully translated jobs.xml
minor changes in businesses, imenu, main and player.xml
1424/1425 translated, as no proposition needed in Latvian at imenu.xml item_name_preposition and it throws an error if string is left empty
> [lv-LV] jobs.xml + minor changes | 100%

- businesses.xml
- jobs.xml
Added missing de-DE translations to businesses.xml & jobs.xml
> Completed de-DE translations

- player.xml
- specialitems.xml
- vehicles.xml
player.xml, vehicles.xml, and specialitems.xml (100% Completed)
All files are fully translated, making the content ready for seamless integration and use.
> [hi-Latn] player.xml, specialitems.xml, vehicles.xml (100% Completed)

- businesses.xml
- player.xml
- vehicles.xml
Reverts Sasino97/gta-cnr-localization#168
Okay I need to revert this, because it regresses the master branch by a lot (lots of other translations lost)
> Revert "arabic translation"

- businesses.xml
- jobs.xml
- main.xml
- player.xml
**_All files are fully translated, making the content ready for seamless integration and use._**
> business.xml and main.xml (100% Completed)
